management:
  endpoint:
    health:
      show-details: always
  health:
    probes:
      enabled: true
org:
  jobrunr:
    background-job-server:
      enabled: true
      worker_count: '1'
    dashboard:
      enabled: true
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:shcdb
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

app:
  resources:
#    - identifier: 1
#      title: SOGIS WMS (Prod)
#      url: https://geo.so.ch/wms
#      #url: http://map.geo.gl.ch/ows/mainmap
#      type: OGC_WMS
#      runFrequency: 0 * * * *
#      active: true
#      probesVars:
#        - identifier: 11
#          probeClass: ch.so.agi.healthcheck.probe.WmsGetCaps
#          parameters: "{\"service\": \"WMS\", \"version\": \"1.3.0\"}"
#          checksVars:
#            - identifier: 111
#              checkClass: ch.so.agi.healthcheck.check.HttpStatusNoError
#              parameters: 
#            - identifier: 112
#              checkClass: ch.so.agi.healthcheck.check.HasUniqueWmsLayerIdentifiers
#              parameters: 
#            - identifier: 113
#              checkClass: ch.so.agi.healthcheck.check.HttpHasHeaderValue
#              parameters: "{\"headerName\": \"content-type\", \"headerValue\": \"text/xml\"}"
#            - identifier: 114
#              checkClass: ch.so.agi.healthcheck.check.XmlParse
#              parameters: 
#            - identifier: 115
#              checkClass: ch.so.agi.healthcheck.check.ContainsStrings
#              parameters: "{\"strings\": \"WMS_Capabilities,Geoinformation,AGI\"}"
#            - identifier: 116
#              checkClass: ch.so.agi.healthcheck.check.NotContainsStrings
#              parameters: "{\"strings\": \"<ServiceException,LayerNotDefined\"}"
#            - identifier: 117
#              checkClass: ch.so.agi.healthcheck.check.HttpStatusMatch
#              parameters: "{\"statusCode\": \"204\"}"
#        - identifier: 12
#          probeClass: ch.so.agi.healthcheck.probe.WmsGetMap
#          parameters: "{\"format\": \"image/png\", \"transparent\": \"true\", \"layers\": \"ch.so.agi.av.grundstuecke\", \"styles\": \"\", \"crs\": \"EPSG:2056\", \"width\": \"200\", \"height\": \"200\", \"bbox\": \"2607800.0,1228200.0,2608000.0,1228400.0\"}"
#          checksVars:
#            - identifier: 121
#              checkClass: ch.so.agi.healthcheck.check.HttpHasImageContentType
#              parameters: 
#            - identifier: 122
#              checkClass: ch.so.agi.healthcheck.check.NotContainsStrings
#              parameters: "{\"strings\": \"<ServiceException,LayerNotDefined\"}"
#        - identifier: 13
#          probeClass: ch.so.agi.healthcheck.probe.WmsGetMap
#          parameters: "{\"format\": \"image/png\", \"transparent\": \"true\", \"layers\": \"ch.so.arp.nutzungsplanung.erschliessungsplanung.verkehrsflaechen\", \"styles\": \"\", \"crs\": \"EPSG:2056\", \"width\": \"200\", \"height\": \"200\", \"bbox\": \"2607800.0,1228200.0,2608000.0,1228400.0\"}"
#          checksVars:
#            - identifier: 131
#              checkClass: ch.so.agi.healthcheck.check.HttpHasImageContentType
#              parameters: 
#            - identifier: 132
#              checkClass: ch.so.agi.healthcheck.check.ContainsStrings
#              parameters: "{\"strings\": \"<ServiceException,LayerNotDefined\"}"
#        - identifier: 14
#          probeClass: ch.so.agi.healthcheck.probe.WmsGetMapAll
#          parameters: "{\"format\": \"image/png\", \"transparent\": \"true\", \"crs\": \"EPSG:2056\", \"width\": \"200\", \"height\": \"200\", \"bbox\": \"2607800.0,1228200.0,2608000.0,1228400.0\"}"
#          checksVars:
#            - identifier: 141
#              checkClass: ch.so.agi.healthcheck.check.HttpHasImageContentType
#              parameters: 
#    - identifier: 2
#      title: SOGIS OEREB V1 (Prod)
#      url: https://geo.so.ch/api/oereb/
#      type: OEREB_V1
#      runFrequency: 0 * * * *
#      active: true
#      probesVars:
#        - identifier: 21
#          probeClass: ch.so.agi.healthcheck.probe.OerebV1GetEgridByCoord
#          parameters: "{\"format\": \"xml\", \"coord\": \"XY=2600478,1215428\"}"
#          checksVars:
#            - identifier: 201
#              checkClass: ch.so.agi.healthcheck.check.HttpStatusNoError
#              parameters: 
#            - identifier: 202
#              checkClass: ch.so.agi.healthcheck.check.OerebV1GetEgridValidator
#              parameters: 
#        - identifier: 22
#          probeClass: ch.so.agi.healthcheck.probe.OerebV1GetEgridByCoord
#          parameters: "{\"format\": \"xml\", \"coord\": \"XY=2700478,1215428\"}"
#          checksVars:
#            - identifier: 221
#              checkClass: ch.so.agi.healthcheck.check.HttpStatusMatch
#              parameters: "{\"statusCode\": \"204\"}"
#    - identifier: 3
#      title: SOGIS Dataproduct Service (Prod)
#      url: https://geo.so.ch/api/search/v2/
#      type: WWW_LINK
#      runFrequency: 0 * * * *
#      active: true
#      probesVars:
#        - identifier: 31
#          probeClass: ch.so.agi.healthcheck.probe.HttpGetQuery
#          parameters: "{\"query\": \"searchtext=erschliessungsplanung&filter=foreground&limit=5\"}"
#          checksVars:
#            - identifier: 301
#              checkClass: ch.so.agi.healthcheck.check.HttpStatusNoError
#              parameters: 
#            - identifier: 302
#              checkClass: ch.so.agi.healthcheck.check.NotContainsStrings
#              parameters: "{\"strings\": \"verkehrsflaechen\"}"
#            - identifier: 303
#              checkClass: ch.so.agi.healthcheck.check.JsonParse
#              parameters: 
    - identifier: 4
      title: SOGIS INTERLIS Modellablage (Prod)
      url: https://geo.so.ch/models/
      type: ILI_REPO
      runFrequency: 0 * * * *
      active: true
      probesVars:
        - identifier: 41
          probeClass: ch.so.agi.healthcheck.probe.IliRepoGet
          parameters: 
          checksVars:
            - identifier: 401
              checkClass: ch.so.agi.healthcheck.check.HttpStatusNoError
              parameters: 
#            - identifier: 402
#              checkClass: ch.so.agi.healthcheck.check.CheckRepoIlis
#              parameters: 
    - identifier: 5
      title: VSA INTERLIS Modellablage (Prod)
      url: https://vsa.ch/models
      type: ILI_REPO
      runFrequency: 0 * * * *
      active: true
      probesVars:
        - identifier: 51
          probeClass: ch.so.agi.healthcheck.probe.IliRepoGet
          parameters: 
          checksVars:
            - identifier: 501
              checkClass: ch.so.agi.healthcheck.check.HttpStatusNoError
              parameters: 
            - identifier: 502
              checkClass: ch.so.agi.healthcheck.check.CheckRepoIlis
              parameters: 
